### PR TITLE
feat: Add documents trash management page - EXO-76028

### PR DESCRIPTION
**Pull request by sofyenne**

### CODE REVIEW

**Review by rdenarie — DISMISSED** [review]
Can you explain briefly how the property eXo.env.portal.documentsTrashNavigationEnabled will be used ?
In the task : 
Values:
True: I display the new page in the administration menu
False: I don't have the Trash page in the administration menu

But I'm not sure to understand what you want to do

**Review by rdenarie — COMMENTED** [review]
Can you explain briefly how the property eXo.env.portal.documentsTrashNavigationEnabled will be used ?
In the task : 
Values:
True: I display the new page in the administration menu
False: I don't have the Trash page in the administration menu

But I'm not sure to understand what you want to do

**Comment by sofyenne** [comment]
> Can you explain briefly how the property eXo.env.portal.documentsTrashNavigationEnabled will be used ? In the task : Values: True: I display the new page in the administration menu False: I don't have the Trash page in the administration menu
> 
> But I'm not sure to understand what you want to do

You know that the page and navigation are added through the XML configuration. Therefore, we can't prevent the navigation from being displayed using a feature flag in the XML configuration. The idea is to use the added property to prevent the navigation from being displayed in the navigation tree component when the property is set to false!

**Comment by sofyenne** [comment]
@rdenarie  Pull request updated!

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
